import Head from 'next/head';
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Script from 'next/script';
import Brand from "../public/brand1.jpg";
import styles from '@/styles/Home.module.css'
import { useState } from 'react';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  const [blogs, setBlogs] = useState(props.allBlogs)
  return (
    <>
      <Head>
        <title>Blog - Coding Hunter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next-js , huntingcoder , blog , hunting coder" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <script src="./alert.js" strategy="lazyOnload"></script> */ }

      <main>
        <style>{
          `.col{
          color : yellow
          }
          `}

        </style>

        <section className={ styles.blogSection }>
          <Image className={ styles.myimg } src={ Brand } width={ 200 } height={ 200 } alt="codingHunter"></Image>
          <h1 className=''>Hunting Coder</h1>
          {/* <img className={styles.myimg} src='/brand1.jpg' alt="" width={300} height={150} /> */ }
          <p className='myspan'>A blog for hunting coders by hunting coder</p>
          <div className={ styles.blog }>
            <h2>Our popular Blogs</h2>

            {
              blogs && blogs.length > 0 && blogs.map((blogitem, index) => {
                return <div className={ styles.blogItems } key={ index }>
                  <Link href={ `blogposts/${blogitem.slug}` }><h2>{ blogitem.title }</h2>
                    <p>{ blogitem.content.substr(0, 140) }...</p>
                    <button className={ styles.btn } type='submit'>Read More</button></Link>
                </div>
              })
            }

          </div>
        </section>
      </main>
    </>
  )
}

// PRE RENDERING IN NEXT JS 
// 2 Second Method for calling Api in next js is SSR server side rendering 
export async function getServerSideProps(){
  let data = await fetch(`http://localhost:3000/api/blogs`)
  let allBlogs = await data.json();
    return{
      props : {allBlogs}
    }
}
